name: OpenXES CLI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.kts'
      - '.github/workflows/build.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.kts'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openxes-cli
          path: build/libs/openxes-cli.jar

