name: OpenXES CLI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.kts'
      - '.github/workflows/build.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.kts'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openxes-cli
          path: build/libs/openxes-cli.jar

      - name: Get version
        id: get_version
        run: |
          echo version=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}') >> $GITHUB_OUTPUT

      - name: Assign repository tag
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push --tags

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/openxes-cli.jar
          tag_name: ${{ steps.get_version.outputs.version }}
          body: |
            # OpenXES CLI
            This is the OpenXES CLI version ${{ steps.get_version.outputs.version }}.